#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.2 on Thu Mar  7 05:09:30 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainMenuFrameClass(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainMenuFrameClass.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MINIMIZE | wx.MINIMIZE_BOX | wx.RESIZE_BORDER | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        
        # Menu Bar
        self.MainMenuFrame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_NEW, "New Contact File...", "")
        self.Bind(wx.EVT_MENU, self.NewContactFileEventHandler, id=wx.ID_NEW)
        wxglade_tmp_menu.Append(wx.ID_OPEN, "Open Contact File...", "")
        self.Bind(wx.EVT_MENU, self.OpenContactFileEventHandler, id=wx.ID_OPEN)
        wxglade_tmp_menu.Append(wx.ID_SAVE, "Save", "")
        self.Bind(wx.EVT_MENU, self.SaveContactFileEventHandler, id=wx.ID_SAVE)
        wxglade_tmp_menu.Append(wx.ID_SAVEAS, "Save As...", "")
        self.Bind(wx.EVT_MENU, self.SaveAsContactFileEventHandler, id=wx.ID_SAVEAS)
        self.MainMenuFrame_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.MainMenuFrame_menubar.Append(wxglade_tmp_menu, "Edit")
        wxglade_tmp_menu = wx.Menu()
        self.MainMenuFrame_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.MainMenuFrame_menubar)
        # Menu Bar end
        self.MainMenuPanel = wx.Panel(self, wx.ID_ANY)
        self.ManageContactsButton = wx.Button(self.MainMenuPanel, wx.ID_ANY, "Manage Contacts")
        self.PrintLabelsButton = wx.Button(self.MainMenuPanel, wx.ID_ANY, "Print Labels")
        self.OtherActivityButton = wx.Button(self.MainMenuPanel, wx.ID_ANY, "Other Activities")
        self.QuitButton = wx.Button(self.MainMenuPanel, wx.ID_QUIT, "Quit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.ManageContactsButtonHandler, self.ManageContactsButton)
        self.Bind(wx.EVT_BUTTON, self.PrintLabelsButtonHandler, self.PrintLabelsButton)
        self.Bind(wx.EVT_BUTTON, self.OtherActivitiesButtonEventHandler, self.OtherActivityButton)
        self.Bind(wx.EVT_BUTTON, self.QuitButtonEventHandler, self.QuitButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainMenuFrameClass.__set_properties
        self.SetTitle("Main Menu")
        self.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "DejaVu Sans"))
        self.ManageContactsButton.SetToolTip("Add, change, or delete contacts")
        self.PrintLabelsButton.SetToolTip("Choose this button to print labels for the contacts")
        self.OtherActivityButton.SetToolTip("Other activities such as import or export contacts, etc.")
        self.QuitButton.SetToolTip("Leave the Christmas Label program")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainMenuFrameClass.__do_layout
        sizer_1 = wx.WrapSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        label_1 = wx.StaticText(self.MainMenuPanel, wx.ID_ANY, "Main Menu")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_2.Add(label_1, 0, wx.ALIGN_CENTER, 0)
        sizer_2.Add(self.ManageContactsButton, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_2.Add(self.PrintLabelsButton, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_2.Add(self.OtherActivityButton, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_2.Add(self.QuitButton, 0, wx.ALIGN_CENTER | wx.EXPAND, 0)
        self.MainMenuPanel.SetSizer(sizer_2)
        sizer_1.Add(self.MainMenuPanel, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def FileMenuEventHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'FileMenuEventHandler' not implemented!")
        event.Skip()

    def NewContactFileEventHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'NewContactFileEventHandler' not implemented!")
        event.Skip()

    def OpenContactFileEventHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'OpenContactFileEventHandler' not implemented!")
        event.Skip()

    def SaveContactFileEventHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'SaveContactFileEventHandler' not implemented!")
        event.Skip()

    def SaveAsContactFileEventHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'SaveAsContactFileEventHandler' not implemented!")
        event.Skip()

    def ManageContactsButtonHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'ManageContactsButtonHandler' not implemented!")
        event.Skip()

    def PrintLabelsButtonHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'PrintLabelsButtonHandler' not implemented!")
        event.Skip()

    def OtherActivitiesButtonEventHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'OtherActivitiesButtonEventHandler' not implemented!")
        event.Skip()

    def QuitButtonEventHandler(self, event):  # wxGlade: MainMenuFrameClass.<event_handler>
        print("Event handler 'QuitButtonEventHandler' not implemented!")
        event.Skip()

# end of class MainMenuFrameClass

class ChristmasLabelsApp(wx.App):
    def OnInit(self):
        self.MainMenuFrame = MainMenuFrameClass(None, wx.ID_ANY, "")
        self.SetTopWindow(self.MainMenuFrame)
        self.MainMenuFrame.Show()
        return True

# end of class ChristmasLabelsApp

if __name__ == "__main__":
    ChristmasLabels = ChristmasLabelsApp(0)
    ChristmasLabels.MainLoop()
